name: Version Bump on Push

on:
  push:
    branches: [main]
    paths-ignore:
      - "**/*.md"
      - ".github/**"

jobs:
  bump-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Extract and bump version
        id: version
        run: |
          # Extrai a versão atual do main.go
          CURRENT=$(grep 'Version:' main.go | sed 's/.*Version: "\([^"]*\)".*/\1/')
          echo "Current version: $CURRENT"

          # Separa os componentes da versão
          IFS='.' read -r MAJOR MINOR PATCH <<< "$CURRENT"

          # Incrementa o patch
          NEW_PATCH=$((PATCH + 1))
          NEW_VERSION="$MAJOR.$MINOR.$NEW_PATCH"

          echo "New version: $NEW_VERSION"
          echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT

          # Atualiza o arquivo
          sed -i "s/Version: \"$CURRENT\"/Version: \"$NEW_VERSION\"/" main.go

      - name: Commit and tag
        run: |
          NEW_VERSION="${{ steps.version.outputs.new_version }}"

          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"

          git add main.go
          git commit -m "🚀 Bump version to v$NEW_VERSION"
          git tag "v$NEW_VERSION"
          git push origin main --tags
